Ei 513 unit of work
SkillsFundingAgency/das-employer-incentives pull request #130
Opened 2020-11-11 20:01 UTC by MichaelYoung1981

2020-11-11 20:23 UTC, David-B-Read approved these changes

2020-11-12 08:46 UTC, Stephek requested changes
Looks good.  Just one comment.

2020-11-12 08:46 UTC, Stephek commented on src/SFA.DAS.EmployerIncentives.Commands/ServiceCollectionExtensions.cs
> +                .Decorate(typeof(ICommandHandler<>), typeof(CommandHandlerWithUnitOfWork<>));
I think this should be the inner decorator.  So the order would be 

CommandHandlerWithLogging -> CommandHandlerWithValidator -> CommandHandlerWithRetry -> CommandHandlerWithDistributedLock -> CommandHandlerWithUnitOfWork -> handler

So needs to be moved to the first in the list.

2020-11-12 08:51 UTC, Stephek requested changes

2020-11-12 08:51 UTC, Stephek commented on src/SFA.DAS.EmployerIncentives.Commands/ServiceCollectionExtensions.cs
> +        public static IServiceCollection AddEntityFrameworkForEmployerIncentives(this IServiceCollection services, IConfiguration configuration)
Is configuration being used?

2020-11-12 09:44 UTC, Stephek approved these changes

2020-11-12 12:20 UTC, merged