EI-478 / EI-226 Validation: identify whether an apprenticeship is provider data locked + JSON inputs for acceptance tests
SkillsFundingAgency/das-employer-incentives pull request #144
Opened 2020-11-18 18:00 UTC by ruslanss

…vider data locked + JSON inputs for acceptance tests

2020-11-18 19:00 UTC, Stephek requested changes

2020-11-19 08:57 UTC, ruslanss commented on src/SFA.DAS.EmployerIncentives.Commands/Persistence/LearnerDomainRepository.cs
> +            var nextPayment = incentive.PendingPayments.Where(pp => pp.PaymentMadeDate == null)
i disagree. i think we should be enriching our domain and not the command handlers. NextDuePayment is property in our domain only as it's based on the Earnings Calc in our system alone. 
only thing i would do is probably move this property out of the Learner and into the Incentive model, what do yo say?

2020-11-19 10:06 UTC, Stephek commented on src/SFA.DAS.EmployerIncentives.Commands/Persistence/LearnerDomainRepository.cs
> +            var nextPayment = incentive.PendingPayments.Where(pp => pp.PaymentMadeDate == null)
The command handlers are the use case. Learner is an aggregate root so when re-hyrated it should contain it current state.  If you call Find then that won't happen.  it shouldn't rely on another entity to be hydrated.  The next payment is a specific use case not part of this entity unless it's stored as part of the entity.  If it was stored as part of the entity then this logic would only be required on creation which again is a specific use case.

2020-11-19 11:26 UTC, Stephek approved these changes
Nice work

2020-11-19 11:44 UTC, merged