EI 676 branched from 478 - Employer withdrawl
SkillsFundingAgency/das-employer-incentives pull request #172
Opened 2020-12-08 18:15 UTC by Stephek

2020-12-10 15:07 UTC, David-B-Read commented on src/SFA.DAS.EmployerIncentives.Api.AcceptanceTests/Features/WithdrawlByEmployer.feature
> +	When the apprenticeship application is withdrawn from the scheme
Withdrawl is at an apprenticeship level

2020-12-11 14:48 UTC, David-B-Read approved these changes

2020-12-11 16:22 UTC, ruslanss commented on src/SFA.DAS.EmployerIncentives.Api.AcceptanceTests/Features/WithdrawlByEmployer.feature
> +	When the apprenticeship application is withdrawn from the scheme
...and is spelt "withdrawal" :)

2020-12-14 10:11 UTC, ruslanss requested changes

2020-12-14 14:22 UTC, Stephek commented on src/SFA.DAS.EmployerIncentives.Domain/IncentiveApplications/IncentiveApplication.cs
> +        public void EmployerWithdrawn(Apprenticeship apprenticeship, ServiceRequest serviceRequest)
Update to EmployerWithdrawal

2021-01-06 19:40 UTC, merged