Ei 1705 employment check error codes
SkillsFundingAgency/das-employer-incentives pull request #487
Opened 2022-04-04 16:29 UTC by David-B-Read

2022-04-19 16:22 UTC, ruslanss requested changes

2022-04-19 16:22 UTC, ruslanss commented on src/SFA.DAS.EmployerIncentives.Data/ApprenticeshipIncentives/Map/DataExtensions.cs
> +                RefreshDate = model.RefreshDate
this is duplicated

2022-04-19 16:22 UTC, ruslanss commented on src/SFA.DAS.EmployerIncentives.Database/Scripts/Generate.CompliancePausedEmploymentCheckFailuresReport.sql
> +FROM incentives.ApprenticeshipIncentive ai
is this relevant to this feature?

2022-04-19 16:22 UTC, ruslanss commented on src/SFA.DAS.EmployerIncentives.Database/Scripts/Generate.JetReport.sql
>    FROM (
is this relevant?

2022-04-19 16:57 UTC, David-B-Read commented on src/SFA.DAS.EmployerIncentives.Data/ApprenticeshipIncentives/Models/ApprenticeApplication.cs
> +        public EmploymentCheckResultError? SecondEmploymentCheckErrorType { get; set; }
Duplicated with what? This is an EF model that's mapped to the incentives.ApprenticeApplications view

2022-04-27 09:40 UTC, ruslanss approved these changes

2022-05-13 10:58 UTC, merged