Fix-  Stopped messages getting published twice
SkillsFundingAgency/das-employer-incentives pull request #74
Opened 2020-08-26 13:46 UTC by Pauljgraham

Removed the MultiEventPublisher and replaced it with IEventPublisher

2020-08-26 14:34 UTC, David-B-Read approved these changes

2020-08-26 14:37 UTC, MichaelYoung1981 requested changes
We shouldn't really be using IEventPublisher either as it doesn't include the message in the Unit of Work.  There is a UnitOfWorkContext class (I think!) that we should use instead so the messages don't get published if the transaction fails.

2020-09-01 08:33 UTC, Stephek commented
> We shouldn't really be using IEventPublisher either as it doesn't include the message in the Unit of Work. There is a UnitOfWorkContext class (I think!) that we should use instead so the messages don't get published if the transaction fails.

IEventPublisher just adds messages to an in memory collection which is then used by the UOW to publish the messages.  It makes it more intuitive that you are publishing an event I guess.

2020-09-01 08:56 UTC, MichaelYoung1981 approved these changes

2020-09-11 09:12 UTC, merged