EI-279 Update VRF case details for new applications Job + update VRF case details for Legal Entity
SkillsFundingAgency/das-employer-incentives pull request #83
Opened 2020-09-03 10:15 UTC by ruslanss

2020-09-08 15:11 UTC, David-B-Read approved these changes

2020-09-09 08:50 UTC, Stephek requested changes

2020-09-09 08:50 UTC, Stephek commented on src/SFA.DAS.EmployerIncentives.Api.AcceptanceTests/Steps/UpdateVrfCaseDetailsForLegalEntitySteps.cs
> +    [Binding]
Please add a feature scope.

2020-09-09 08:50 UTC, Stephek commented on src/SFA.DAS.EmployerIncentives.Commands/Persistence/AccountDomainRepository.cs
> +        public async Task<IEnumerable<Account>> GetByLegalEntityId(long legalEntityId)
This shouldn't be here.  Use the existing AccountQueryRepository repository in the command handler to get the account Id for the legal entity in the command handler then use the IAccountDomainRepository.Find method.  The code already exists.

2020-09-09 08:50 UTC, Stephek commented on src/SFA.DAS.EmployerIncentives.Commands/Persistence/IAccountDomainRepository.cs
> +        Task<IEnumerable<Account>> GetByLegalEntityId(long legalEntityId);
As above.  Not required.

2020-09-28 14:40 UTC, closed without merging